blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # GET->
    path('', views.post_list, name='post_list'),
    #path('', views.PostListView.as_view(), name='post_list'),
    # GET ->
    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name='post_detail'),
    # POST-> Share post via email medium
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    # POST -> comment
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    # GET-> Only renders html
    path('about/', views.about_me, name='about_me'),
    # Posts by tag
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # making the default route be pointing to the blogs
    path('', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
    
    tags = TaggableManager()
    
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    # Add a relationship to the user
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    
    objects = models.Manager() # default
    published = PublishManager()
    
    class Meta:
        ordering = ['-publish']
        
        indexes = [
            models.Index(fields=['-publish'])
        ]
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year, self.publish.month, self.publish.day, self.slug])
    
    
    def about_me():
        return 'blog:about_me'
    
    
class Comment(models.Model):
    # define the relationship to the post data model
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ['created']
        
        indexes = [
            models.Index(fields=['created']),
        ]
        
    def __str__(self) -> str:
        return f'Comment by {self.name} on {self.post}'
    
    

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)
    
    
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, Comment
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name: str = 'posts'
    paginate_by: int = 3
    template_name: str = 'blog/post/list.html'
    


def post_list(request, tag_slug =None):
    tag = None
    post_list = Post.published.all()
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    
    return render(request, 'blog/post/list.html', {'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    
    comments = post.comments.filter(active=True)
    form = CommentForm()
    
    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, 'form': form})


def about_me(request):
    return render(request,'blog/about.html')

# 
def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        # form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # ssend the email
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'your_account@gmail.com',
                      [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
        
    return render(request, 'blog/post/share.html', {'post': post, 'form': form})

# TODO: Decide whether or not we should keep the commenting system in place
@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        
        comment.post = post
        
        comment.save()
        
    return render(request, 'blog/post/comment.html', {'post': post, 'form': form, 'comment': comment})

blog/templates/blog/about.html
<section id="about">  

  <div class="row section-intro">
    <div class="col-twelve">
      <div class="intro-info">

        <img src="https://secure.gravatar.com/avatar/5f9a29a8407e88a611b5bd004408018e" alt="Profile Picture">

        <p class="lead">
        
          Eliot began programming early in his college experience which further fueled his interest in Computer Scinece. In the Marine Corps, he continued programming as a hobby while learning about networking and security.

          After leaving the military service, Eliot began working as a software engineer in the Albuquerque, New Mexico area and soon after that he secured a position at Sandia National Laboratory. Working for the premier 
          nuclear lab in the united states, he began work in Angular development by assisting in creating a RSS News feed application that feed the entire Sandia National Labs workforce. He also began work in C# .Net application
          development creating several applications for scientists to upgrade their current work by adding a digital manner of analysis and accident prevention.  

          CONTINUE HERE NEXT TIME
        
        
        
        </p>
      </div>   			

    </div>   		
  </div> <!-- /section-intro -->

  <div class="row about-content">

    <div class="col-six tab-full">

      <h3>Summary</h3>
      <p>Lorem ipsum Qui veniam ut consequat ex ullamco nulla in non ut esse in magna sint minim officia consectetur nisi commodo ea magna pariatur nisi cillum.</p>

      <ul class="info-list">
        <li>
          <strong>Full-name:</strong>
          <span>Yev</span>
        </li>
      
        <li>
          <strong>Job:</strong>
          <span>Developer</span>
        </li>
        <li>
          <strong>Website:</strong>
          <span>www.TBD.com</span>
        </li>
        <li>
          <strong>Email:</strong>
          <span>me@email.com</span>
        </li>

      </ul> <!-- /info-list -->

    </div>

    <div class="col-six tab-full">

      <h3>Skills & Projects</h3>
      <p>Lorem ipsum Qui veniam ut consequat ex ullamco nulla in non ut esse in magna sint minim officia consectetur nisi commodo ea magna pariatur nisi cillum.</p>

     <ul class="skill-bars">
        <li>
          <div class="progress percent90"><span>90%</span></div>
          <strong>Python</strong>
        </li>
        <li>
          <div class="progress percent85"><span>85%</span></div>
          <strong>Javascript</strong>
        </li>
        <li>
          <div class="progress percent70"><span>70%</span></div>
          <strong>Django</strong>
        </li>
        <li>
          <div class="progress percent95"><span>95%</span></div>
          <strong>Golang</strong>
        </li>
        <li>

          <div class="progress percent75"><span>75%</span></div>
          <strong>Your Mom</strong>
        </li>
   
     </ul> <!-- /skill-bars -->		

    </div>
    <p>
      <a href="{% url "blog:post_list" %}">
        Back
      </a>
    </p>

  </div>
</section>

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/blog.css" %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <div class='container' id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div class='navbar' id="sidebar">
    Learn more about me.
    <a href="/about">
      About me
    </a>
  </div>
</body>
</html>

blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}
{% block title %}Add a comment{% endblock %}
{% block content %}
  {% if comment %}
    <h2>Your comment has been added.</h2>
    <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
  {% else %}
    {% include "blog/post/includes/comment_form.html" %}
  {% endif %}
{% endblock %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|linebreaks }}
  <p>
    <a href="{% url "blog:post_share" post.id %}">
      Share this post
    </a>
  </p>
  <p>
    <a href="{% url "blog:post_list" %}">
      Back
    </a>
  </p>
{% endblock %}

blog/templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url "blog:post_comment" post.id %}" method="post">
  {{ form.as_p }}
  {% csrf_token %}
  <p><input type="submit" value="Add comment"></p>
</form>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}Software Architecutre, Design and Development by Eliot{% endblock %}
{% block content %}
  <h1>Software Architecutre, Design and Development by Eliot</h1>
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <div class='card'>
      <div class='card-content'>
        <a href="{{ post.get_absolute_url }}">
          {{ post.title }}
        </a>
        <p class="tags">
          Tags:
          {% for tag in post.tags.all %}
            <a href="{% url "blog:post_list_by_tag" tag.slug %}">
              {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
          {% endfor %}
       </p>
      </div>
      <div class='card-footer'>
        <p class="date">
          Published {{ post.publish }} by {{ post.author }}
        </p>
      </div>
    </div>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
      {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
      {% endif %}
      <span class="current">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
      </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
    </span>
  </div>